apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-models-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 220.1.12.11
    path: /mnt/shared/k8s/ytg
  persistentVolumeReclaimPolicy: Retain
